#! /bin/bash


echo activating venv...
. ./activate

set -e

echo installing pip dependencies
pip install -r requirements.txt

echo running black...
black transcribe_anything tests --exclude 'transcribe_anything/venv'

echo running isort...
isort transcribe_anything tests

echo re-running black now
black transcribe_anything tests  --exclude 'transcribe_anything/venv'

# does --clean exist
if [[ $* == *--no-ruff* ]]; then
    echo skipping ruff...
else
    echo running ruff...
    ruff check transcribe_anything tests
fi


echo running mypy...
mypy transcribe_anything tests --exclude 'transcribe_anything/venv'